; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



;NOTES:
;
; JPEDEC Library: (src/JPEGDEC.h)
; edit JPEGDEC.h and change the values of
; JPEG_FILE_BUF_SIZE and MAX_BUFFERED_PIXELS to 4096
;
; Arduino_GFX Library (src/databus/ES32RGBPanel.h):
; edit Arduino_ESP32RGBPanel.h and switch the defines on line 58 and 59 to
;        #if (!defined(ESP_ARDUINO_VERSION_MAJOR)) || (ESP_ARDUINO_VERSION_MAJOR < 3)
;        //#if (!defined(ESP_ARDUINO_VERSION_MAJOR)) || (ESP_ARDUINO_VERSION_MAJOR >5)
;
; Arduino_GFX Library (src/databus/Arduino_ESP32SPI.h):
; edit Arduino_ESP32SPI.h and comment out the includes of 
;      esp32-hal-periman.h and esp_private/periph_ctrl.h on lines 21 and 22
;              //#include "esp32-hal-periman.h"
;              //#include "esp_private/periph_ctrl.h"
;
[platformio]
default_envs = ESP32-S3-LCD-3-16

[env]
lib_deps = 
    https://github.com/bitbank2/JPEGDEC
    https://github.com/olikraus/U8g2_Arduino
    https://github.com/fbiego/ESP32Time.git
	https://github.com/gpb01/SerialCmd
	https://github.com/moononournation/Arduino_GFX
	https://github.com/holgerlembke/ESPFMfGK
	https://github.com/bblanchon/ArduinoJson
; https://github.com/witnessmenow/file-fetcher-arduino // Replaced with a custom version included in the src directory




[env:ESP32-S3-LCD-3-16]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_ldf_mode = deep
lib_compat_mode = strict

; ESP32-S3 specific build options
board_build.arduino.memory_type = qio_opi
board_build.arduino.memory_freq = 80m
board_build.psram_type = opi

board_build.flash_size = 16MB
board_build.flash_mode = qio
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB
; See https://github.com/espressif/arduino-esp32/blob/master/tools/partitions for options
board_build.partitions = default_16MB.csv 

lib_deps =
	${env.lib_deps}

; Build flags for debugging
build_flags =
  -D CORE_DEBUG_LEVEL=0 ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
	${env.build_flags}
	-I./src/
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 # Set false to use custom VID/PID or true for normal serial debug
	-D CONFIG_ESP_CONSOLE_USB_CDC=y
	-D PASSWORD='"ota_password"' ; Set the OTA password for secure updates.
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=820
	-D PORTRAIT_SCREEN=true ; Swaps the WxH so the marquee directories are more human readable. 

; Debug configuration for ESP32-S3
; For debugging use Zadig to change the ESB32 USB drivers to:	
;			 USB Interface 0 = WinUSB driver
;			 USB Interface 2 = libusbK driver
;build_type = debug
;debug_tool = esp-builtin
;debug_init_break = break setup


; Monitor settings for debugging
monitor_speed = 115200
monitor_filters = esp32_exception_decoder


; Upload configuration for OTA updates
; Inital install needs to be done via USB, then subsequent updates can be done OTA
;upload_port = mr_marquee.local
;upload_protocol = espota
;upload_flags =
;    --auth=ota_password ; Set the password to match the define above
;upload_speed = 921600



[env:cyd]
lib_deps =
	${env.lib_deps}

platform = espressif32
board = esp32dev
board_build.filesystem = spiffs # littlefs # fatfs
framework = arduino
lib_ldf_mode = deep
lib_compat_mode = strict

board_build.partitions = min_spiffs.csv
build_flags = 
	-I./src/
	-I./src/ui/
	-D USER_SETUP_LOADED
	-D ILI9341_2_DRIVER
	-DU SE_HSPI_PORT
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MISO=12
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=-1
	-D TFT_BL=21
	-D TFT_BACKLIGHT_ON=HIGH
	-D TFT_BACKLIGHT_OFF=LOW
	-D LOAD_GLCD
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=820
	-D PORTRAIT_SCREEN=true ; Swaps the WxH so the marquee directories are more human readable. 

; Debug configuration for ESP32-S3
; For debugging use Zadig to change the ESB32 USB drivers to:	
;			 USB Interface 0 = WinUSB driver
;			 USB Interface 2 = libusbK driver
;build_type = debug
;debug_tool = esp-builtin
;debug_init_break = break setup


; Monitor settings for debugging
monitor_speed = 115200
monitor_filters = esp32_exception_decoder


; Upload configuration for OTA updates
; Inital install needs to be done via USB, then subsequent updates can be done OTA
;upload_port = mr_marquee.local
;upload_protocol = espota
;upload_flags =
;    --auth=ota_password ; Set the password to match the define above
;upload_speed = 921600

