; PlatformIO Project Configuration File
;

;NOTES:
; The ESP32-S3 support in the Arduino_GFX library is currently broken due to changes in the underlying
; ESP32 Arduino core. To get it working, you need to make the following changes to the library code:
;
; Arduino_GFX Library (src/databus/ES32RGBPanel.h):
; edit Arduino_ESP32RGBPanel.h and switch the defines on line 58 and 59 to
;        #if (!defined(ESP_ARDUINO_VERSION_MAJOR)) || (ESP_ARDUINO_VERSION_MAJOR < 3)
;        //#if (!defined(ESP_ARDUINO_VERSION_MAJOR)) || (ESP_ARDUINO_VERSION_MAJOR >5)
;
; Arduino_GFX Library (src/databus/Arduino_ESP32SPI.h):
; edit Arduino_ESP32SPI.h and comment out the includes of 
;      esp32-hal-periman.h and esp_private/periph_ctrl.h on lines 21 and 22
;              //#include "esp32-hal-periman.h"
;              //#include "esp_private/periph_ctrl.h"
;
[platformio]
src_dir = src
; Uncomment to build Waveshare ESP32-S3 3.16" version
;default_envs = ESP32-S3-LCD-3-16
default_envs = ESP32-S3-HUB75
;default_envs = cyd

; Uncomment to build the correct sacled images for the selected display
;data_dir = data_waveshare ; Images scaled for Waveshare
;data_dir = data_cyd ; Images scaled for CYD
;data_dir = data_hub75 ; Images scaled for HUB75
data_dir = ${PROJECT_DIR}/data_${PIOENV} ; Use environment variable to select the correct data directory for each build environment (thankyou jonsummers)

; Global configuration for all environments
[env]
platform = espressif32
framework = arduino
lib_ldf_mode = deep
lib_compat_mode = strict
upload_speed=115200
board_build.filesystem = spiffs

lib_deps = 
    https://github.com/bitbank2/JPEGDEC
    https://github.com/olikraus/U8g2_Arduino
    https://github.com/fbiego/ESP32Time.git
	https://github.com/gpb01/SerialCmd
	https://github.com/holgerlembke/ESPFMfGK
	ArduinoJson
	https://github.com/tzapu/WiFiManager
	https://github.com/plageoj/urlencode

; https://github.com/witnessmenow/file-fetcher-arduino // Replaced with a custom version included in the src directory

build_flags =
	-D CORE_DEBUG_LEVEL=1  			; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
	-D PASSWORD='"ota_password"' 	; Set the OTA password for secure updates.
	-mfix-esp32-psram-cache-issue
	-I./src/

; Debug configuration for ESP32-S3
; For debugging use Zadig to change the ESB32 USB drivers to:	
;			 USB Interface 0 = WinUSB driver
;			 USB Interface 2 = libusbK driver
;build_type = debug
;debug_tool = esp-builtin
;debug_init_break = break setup

; Monitor settings for debugging
monitor_speed = 115200
monitor_filters = default, esp32_exception_decoder

; Upload configuration for OTA updates
; Inital install needs to be done via USB, then subsequent updates can be done OTA
;upload_port = mr_marquee.local
;upload_protocol = espota
;upload_flags =
;    --auth=ota_password ; Set the password to match the define above
;upload_speed = 921600


; Waveshare ESP32-S3 3.16" board
[env:ESP32-S3-LCD-3-16]
board = esp32-s3-devkitc-1

; ESP32-S3 specific build options
board_build.arduino.memory_type = qio_opi
board_build.arduino.memory_freq = 80m
board_build.psram_type = opi

board_build.flash_size = 16MB
board_build.flash_mode = qio
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB
; See https://github.com/espressif/arduino-esp32/blob/master/tools/partitions for options
board_build.partitions = default_16MB.csv 

lib_deps =
	https://github.com/moononournation/Arduino_GFX
	https://github.com/LiquidCGS/FastIMU
	${env.lib_deps}


; Build flags for debugging
build_flags =
	${env.build_flags}
	-D WAVESHARE
	-D USE_IMU  				# Use Inertial Measurement Unit for auto-rotation
	-D IMU_CHIP=QMI8658
	-D IMU_SDA=15
	-D IMU_SCL=7
	-D IMU_ADDRESS=0x6b
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 # Set false to use custom VID/PID or true for normal serial debug
	-D CONFIG_ESP_CONSOLE_USB_CDC=y
	-D BOARD_HAS_PSRAM
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=820
	-D TFT_BL=06
	-D TFT_BACKLIGHT_ON=LOW
	-D TFT_BACKLIGHT_OFF=HIGH
	-D PORTRAIT_SCREEN=true ; Swaps the WxH so the marquee directories are more human readable. 
	-D FOOTER_LINE=270
	-D TRIGGER_PIN=0
	-D DEFAULT_ROTATION=3





; Cheap Yellow Display "CYD" board
[env:cyd]
lib_deps =
	https://github.com/moononournation/Arduino_GFX
	${env.lib_deps}
	;//https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	; bodmer/TFT_eSPI

board = esp32dev

board_build.partitions = min_spiffs.csv
build_flags = 
	${env.build_flags}
	-D USER_SETUP_LOADED
	-D ILI9341_2_DRIVER
	-D USE_HSPI_PORT
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D PORTRAIT_SCREEN=true		; Swaps the WxH so the marquee directories are more human readable. 
	-D TFT_MISO=12				; TFT pins
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=-1
	-D TFT_BL=21
	-D LED_RED=4				; LED pins
	-D LED_GREEN=16
	-D LED_BLUE=17
	-D SD_MOSI=23				; SDCARD pins
	-D SD_MOSO=19
	-D SD_CLK=18
	-D SD_CS=5
	-D FOOTER_LINE=210
	-D LDR=34					; Light dependant resistor
	-D XPT2046_IRQ=36			; Touch pins
	-D XPT2046_MOSI=32
	-D XPT2046_MOSO=39
	-D XPT2046_CLK=25
	-D XPT2046_CS=33
	-D TFT_BACKLIGHT_ON=HIGH
	-D TFT_BACKLIGHT_OFF=LOW
	-D LOAD_GLCD
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D DEFAULT_ROTATION=3


; ESP32-S3 HUB75 board i.e. Adafruit Matrix Portal S3 
[env:ESP32-S3-HUB75]
board = esp32-s3-devkitc-1

platform = espressif32
framework = arduino

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
  
; See https://github.com/espressif/arduino-esp32/blob/master/tools/partitions for options
board_build.partitions = default_8MB.csv

lib_deps =
	https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA
	https://github.com/mrcodetastic/GFX_Lite
	https://github.com/LiquidCGS/FastIMU
	${env.lib_deps}


; Build flags for debugging
build_flags =
	${env.build_flags}
	-D HUB75
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 # Set false to use custom VID/PID or true for normal serial debug
	-D CONFIG_ESP_CONSOLE_USB_CDC=y
	-D BOARD_HAS_PSRAM
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D TFT_WIDTH=64
	-D TFT_HEIGHT=64
	-D PANEL_CHAIN=3
;	-D PIXEL_COLOUR_DEPTH_BITS=6
	-D PORTRAIT_SCREEN=false ; Swaps WxH on file fetchs so the marquee directories are more human readable. 
	-D FOOTER_LINE=10
;	-D USE_IMU  				# Use Inertial Measurement Unit for auto-rotation
;	-D IMU_CHIP=LIS3DH
;	-D IMU_SDA=16
;	-D IMU_SCL=17
;	-D IMU_ADDRESS=0x19
	-D TRIGGER_PIN=7
	-D DEFAULT_ROTATION=0
;	-D SPIRAM_DMA_BUFFER
	-D USE_GFX_LITE

