#!/bin/sh
### BEGIN INIT INFO
# Provides:          mr-marquee
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mr-marquee web server and mDNS server
# Description:       Provides a web server and mDNS server. Enables a remote ESP32 based system 
#                    to find the mister fpga system using the mDNS name mister.local. The remote
#                    can then use HTTP to query the current running core and a setting file.
#                    The web server also shares marquee JPG's. 
### END INIT INFO
 
# Configuration variables
DAEMON="/media/fat/wifiBanner/wifiBanner"
DAEMON_NAME="wifiBanner"
PIDFILE="/var/run/$DAEMON_NAME.pid"
LOGFILE="/var/log/$DAEMON_NAME.log"
 
 
case "$1" in
    start)
        # Start the daemon using start-stop-daemon (handles forking/PID)
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
            --exec $DAEMON >> $LOGFILE 2>&1
        ;;
    stop)
        # Stop the daemon using the PID file
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        # Remove PID file after stopping
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart}"
        exit 1
        ;;
esac
 
exit 0
